// Code generated by paramgen. DO NOT EDIT.
// Source: github.com/ConduitIO/conduit-connector-sdk/tree/main/cmd/paramgen

package destination

import (
	sdk "github.com/conduitio/conduit-connector-sdk"
)

func (Config) Parameters() config.Parameters {
	return map[string]config.Parameter{
		"auth.apiKey": {
			Default:     "",
			Description: "A Weaviate API key.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"auth.mechanism": {
			Default:     "none",
			Description: "mechanism specifies in which way the connector will authenticate to Weaviate.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"none", "apiKey", "wcsCreds"}},
			},
		},
		"auth.wcsCreds.password": {
			Default:     "",
			Description: "WCS password",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"auth.wcsCreds.username": {
			Default:     "",
			Description: "WCS username",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"class": {
			Default:     "",
			Description: "The class name as defined in the schema. A record will be saved under this class unless it has the `weaviate.class` metadata field.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"endpoint": {
			Default:     "",
			Description: "Host of the Weaviate instance.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationRequired{},
			},
		},
		"generateUUID": {
			Default:     "",
			Description: "Whether a UUID for records should be automatically generated. The generated UUIDs are MD5 sums of record keys.",
			Type:        config.ParameterTypeBool,
			Validations: []config.Validation{},
		},
		"moduleHeader.name": {
			Default:     "",
			Description: "name of the header configuring a module (e.g. `X-OpenAI-Api-Key`)",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"moduleHeader.value": {
			Default:     "",
			Description: "value for header given in `moduleHeader.name`.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{},
		},
		"scheme": {
			Default:     "https",
			Description: "scheme of the Weaviate instance.",
			Type:        config.ParameterTypeString,
			Validations: []config.Validation{
				config.ValidationInclusion{List: []string{"http", "https"}},
			},
		},
	}
}
