name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Unit tests
        run: make test GOTEST_FLAGS="-v -count=1"

      - name: Integration tests
        env:
          OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
        run: make test-integration GOTEST_FLAGS="-v -count=1"
