name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        env:
          OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
        run: make test-integration GOTEST_FLAGS="-v -count=1"
